### ISSUE TITLE
Too Many VariantSets

### ISSUE THREAD

**Issue by adamnovak** [glennhickey/hal2sg#8]
hal2sg is producing a VariantSet for every genome in the HAL, but is only putting Alleles into VariantSet 0:

```
INSERT INTO VariantSet VALUES (0, 0, 'Anc0');
INSERT INTO VariantSet VALUES (1, 0, 'ref');
INSERT INTO VariantSet VALUES (2, 0, 'GI568335879');
INSERT INTO VariantSet VALUES (3, 0, 'GI568335954');
INSERT INTO VariantSet VALUES (4, 0, 'GI568335976');
INSERT INTO VariantSet VALUES (5, 0, 'GI568335986');
INSERT INTO VariantSet VALUES (6, 0, 'GI568335989');
INSERT INTO VariantSet VALUES (7, 0, 'GI568335992');
INSERT INTO VariantSet VALUES (8, 0, 'GI568335994');
INSERT INTO VariantSet VALUES (9, 0, 'GI568335997');

INSERT INTO Allele VALUES (0, 0, 'Anc0refChr0');
INSERT INTO Allele VALUES (1, 0, 'Anc0refChr1');
INSERT INTO Allele VALUES (2, 0, 'Anc0refChr2');
INSERT INTO Allele VALUES (3, 0, 'Anc0refChr3');
INSERT INTO Allele VALUES (4, 0, 'Anc0refChr4');
INSERT INTO Allele VALUES (5, 0, 'Anc0refChr5');
INSERT INTO Allele VALUES (6, 0, 'Anc0refChr6');
INSERT INTO Allele VALUES (7, 0, 'Anc0refChr7');
...
```

Instead, it should produce only one VariantSet.

**Comment by glennhickey** [comment]
hal2sg will only put alleles converted from genome Anc0 into VariantSet 0
in that example.  Alleles for genome "ref" will be in VariantSet 1, etc.:

...
INSERT INTO Allele VALUES (54, 0, 'Anc0refChr54');
INSERT INTO Allele VALUES (55, 1, 'ref');
INSERT INTO Allele VALUES (56, 2, 'GI568335879');
...

The logic was that this allows the HAL Genome/Sequence structure to be
preserved in the SQL output (ie I easily can iterate alleles derived from
any desired genome).  This isn't really a factor for the pilot data, but
would seem fairly important for input graphs with multiple chromosomes.
It's an easy change to make hal2sg dump eveything in a single VariantSet,
but I'm concerned about this loss of information..  I'm just curious what
having the multiple VariantSets is breaking? Or if there's another way I
can store HALs Genome/Sequence relationships?

**Comment by adamnovak** [comment]
OK, you are right. I did not manage to find the part of the SQL illustrating this.

```
INSERT INTO Allele VALUES (490, 1, 'ref');
INSERT INTO Allele VALUES (491, 2, 'GI568335879');
INSERT INTO Allele VALUES (492, 3, 'GI568335954');
INSERT INTO Allele VALUES (493, 4, 'GI568335976');
INSERT INTO Allele VALUES (494, 5, 'GI568335986');
INSERT INTO Allele VALUES (495, 6, 'GI568335989');
INSERT INTO Allele VALUES (496, 7, 'GI568335992');
INSERT INTO Allele VALUES (497, 8, 'GI568335994');
INSERT INTO Allele VALUES (498, 9, 'GI568335997');
```

What threw me off initially was the server reporting many Alleles when I asked it to restrict to a certain VariantSet. I forgot that we don't have any of the filters implemented in the server yet.

Closing as bug in user.
